myblog/article/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.category_index, name='categories'),
    path('comment/', views.comment_index, name='comment'),

    path('list/', views.ArticleListView.as_view(), name='uneliste'),
    path('<int:pk>', views.ArticleDetailView.as_view(), name='article-detail'),

    #path('<str:slug>', views.ArticleDetailView.as_view(), name='article-detail'),

]

myblog/myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('', RedirectView.as_view(url='articles/')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/article/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe


class Category(models.Model):
    """Cet objet représente une catégorie ou un genre littéraire."""
    name = models.CharField(max_length=200, help_text='Enter an article category (ex : Actualité)')
    # image_url = models.CharField(max_length=2048, help_text='Enter an image url for the category', null=True, blank=True)
    image_url = models.ImageField(upload_to='images/', help_text='Enter an image url for the article', null=True,
                                  default='')

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ['name']

    def __str__(self):
        """Cette fonction est obligatoirement requise par Django.
           Elle retourne une chaîne de caractère pour identifier l'instance de la classe d'objet."""
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200, help_text='Enter te titles', verbose_name="titres'")
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the article',
                               verbose_name="resumé'")
    content = models.TextField(help_text='Enter the article content', verbose_name="contenu'")
    slug = models.SlugField(max_length=300, help_text='Enter the article slug', null=True, blank=True, default="")
    cover_image_url = models.ImageField(upload_to='images/', help_text='Enter an image url for the article', null=True,
                                        default='')
    thumbnail_image_url = models.CharField(max_length=2048, help_text='Enter an image url for the article', null=True,
                                           default='')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    publish_time = models.DateTimeField(null=True)
    visibily = models.BooleanField(default=False, help_text='Visible de l article')
    file = models.FileField(upload_to='files/', help_text='ajouter un fichier', null=True, blank=True)
    category =  models.ForeignKey(Category, help_text='Select a category for this article', on_delete=models.SET_NULL,
                                 null=True, default='', blank=True)

    @property
    def image_preview(self):
        if self.cover_image_url:
            return mark_safe("<img src={} width='300' height='200' />".format(self.cover_image_url))
        return ""

    def __str__(self):
        return self.title


def get_absolute_url(self):
    """Cette fonction est requise pas Django, lorsque vous souhaitez détailler le contenu d'un objet."""
    return reverse('article-detail', args=[str(self.id)])


class Comment(models.Model):
    author_name = models.CharField(max_length=200)
    content = models.TextField(help_text='Enter the article content')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    article = models.ForeignKey(Article, help_text='Select a article ', on_delete=models.SET_NULL,
                                null=True)

    def __str__(self):
        # return self.author_name
        return self.content

myblog/runserver/models.py
from django.db import models

# Create your models here.

myblog/article/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Article, Category, Comment


class ArticleListView(generic.ListView):
    model = Article
    template_name = 'article.html'
    queryset = Article.objects.filter(title__icontains='2')

    # queryset = Article.objects.all()
    # equivalent contexte avec def
    # context_object_name = 'article'


class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'article_detail.html'


def article_detail(request, primary_key):
    article = get_object_or_404(Article, pk=primary_key)

    context = {
        'article': article
    }
    return render(request, 'article_detail.html', context=context)


def index(request):
    num_articles = Article.objects.all().count()
    num_categories = Category.objects.all().count()
    articles = Article.objects.all()

    context = {
        'num_articles': num_articles,
        'num_categories': num_categories,
        'articles_list': articles
    }
    return render(request, 'index.html', context=context)


def category_index(request):
    categories = Category.objects.all()

    context = {
        'categories_list': categories

    }
    return render(request, 'categories.html', context=context)


def comment_index(request):
    comment = Comment.objects.all()

    context = {
        'comment_list': comment

    }
    return render(request, 'comment.html', context=context)


class CategoryListView(generic.ListView):
    model = Category
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test'] = 'un test en texte'
        context['number'] = 53
        return context

    def get_queryset(self):
        return Category.objects.filter(name__contains=self.kwargs['name'])

myblog/runserver/views.py
from django.shortcuts import render

# Create your views here.

myblog/article/templates/article.html
{% extends "base_generic.html" %}

{% block content %}
   <h2>les articles filtrés </h2>
  <ul>
    <li><strong>Articles:</strong> {{ num_articles }}</li>
    <li><strong>Categories:</strong> {{ num_categories }}</li>
  </ul>

<div class="col-sm-4r">

    <div class="row justifiy-content-start">
        {% for article in article_list %}
        <div class="card" style="width:25rem; margin-top: 20px">
            <img src="{{ article.cover_image_url.url }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }} </h5>
                <p class="card-text">{{ article.category.name }} .</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>




{% endblock %}

myblog/article/templates/article_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1> {{ article.title }}</h1>

  <p><strong>Categorie:</strong> {{ article.category.name }}</p>


<div class="col-sm-4r">
    <div class="row justifiy-content-start">
        <div class="card" style="width:25rem; margin-top: 20px">
            <img src="{{ article.cover_image_url.url }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }} </h5>
                <p class="card-text">{{ article.slug }} .</p>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

myblog/article/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Bibliothèque locale</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body style="margin: 25px">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Tous les Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'uneliste' %}">Tous les Articles View</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'categories' %}">Tous les Catégories</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
 <div>
     {% block content %}
     {% endblock %}
 </div>
</body>
</html>

myblog/article/templates/categories.html
{% extends "base_generic.html" %}

{% block content %}

   <h2>Liste des categories</h2>


<div class="container">
  <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
    <div class="col">
      <div class="p-3 border bg-light">
                <ul>
         {% for category in categories_list %}
              <li> {{ category.name }}  </li>
         {% endfor %}
              </ul>
       </div>
    </div>
  </div>
</div>


{% endblock %}

myblog/article/templates/comment.html
{% extends "base_generic.html" %}

{% block content %}

   <h2>Liste des commentaires</h2>


<div class="container">
  <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
    <div class="col">
      <%if comment_list %}
        <div class="p-3 border bg-light">

                <ul>
         {% for com in comment_list %}
              <li> {{ com.content }}  </li>
         {% endfor %}
              </ul>
        </div>
        <% else %>
        <div class="p-3 border bg-light">

                <ul>
              <li> "pas d article"  </li>
              </ul>
        </div>

      <% endif %>
    </div>
  </div>
</div>


{% endblock %}

myblog/article/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1 xmlns="http://www.w3.org/1999/html">Accueil de mon blog</h1>
<p>Bienvenue dans mon blog </p>
<h2>Contenu dynamique</h2>
<p>La blog dispose des enregistrements suivants:</p>
<ul>
    <li><strong>Articles:</strong> {{ num_articles }}</li>
    <li><strong>Categories:</strong> {{ num_categories }}</li>
</ul>
<h2>Liste des articles</h2>

<div class="col-sm-4r">

    <div class="row justifiy-content-start">
        {% for article in articles_list %}
        <div class="card" style="width:25rem; margin-top: 20px">
            <img src="{{ article.cover_image_url.url }}" class="card-img-top">
            <div class="card-body">
                 <a href="{% url 'article-detail' article.id  %}" class="btn btn-primary">

                    {{ article.title }}

                </a>
                <h5 class="card-title">
                    <p class="card-text">{{ article.slug }} .</p></h5>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}